create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id text not null,
  sender_id text not null,
  message_type text not null check (message_type in ('text', 'audio', 'video')),
  content text not null,
  file_name text,
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_conversation_created_idx
  on public.chat_messages (conversation_id, created_at);

alter table public.chat_messages enable row level security;

create policy "chat messages can be read by authenticated users"
  on public.chat_messages for select to authenticated using (true);

create policy "chat messages can be created by authenticated users"
  on public.chat_messages for insert to authenticated with check (true);

alter publication supabase_realtime add table public.chat_messages;

insert into storage.buckets (id, name, public)
values ('chat-media', 'chat-media', true)
on conflict (id) do nothing;

create policy "chat media can be read"
  on storage.objects for select to authenticated
  using (bucket_id = 'chat-media');

create policy "chat media can be uploaded"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'chat-media');

create table if not exists public.call_signals (
  id bigint generated by default as identity primary key,
  call_id text not null,
  sender_id text not null,
  signal_type text not null check (signal_type in ('offer', 'answer', 'candidate')),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists call_signals_call_created_idx
  on public.call_signals (call_id, created_at);

alter table public.call_signals enable row level security;

create policy "call signals can be read by authenticated users"
  on public.call_signals for select to authenticated using (true);

create policy "call signals can be created by authenticated users"
  on public.call_signals for insert to authenticated with check (true);

alter publication supabase_realtime add table public.call_signals;